thehyve/sesi_site

- modules/sesi_addtogroup/sesi_addtogroup.module
Added "Prevent users from unsubscribing from the GLOBAL group" to existing module sesi_addtogroup
> Added "Prevent users from unsubscribing from the GLOBAL group"

- modules/query_interface/query_interface.filter-variables.js
If no domains are selected for any of the variables, the fulltext search did not work. It does now.
> Bugfix for fulltext search on query screen 

- modules/sesi_addtogroup/sesi_addtogroup.module
Removed link to GLOBAL group from user page
> Global group removed from user/ page

- modules/query_access_rights/query_access_rights.module
Fixed a typo and proper use of DateTime object
> Enabled bug in notification on dataset expiration

- patch/mica_distribution/modules/mica/extensions/mica_opal/mica_opal_view/ServicesOpalFormatter.inc
change of file name while export opal view.
> change of file name while export opal view

- patch/mica_distribution/modules/entity/entity_token.tokens.inc
Apply fix for Integer entity tokens and number_format() issues in Entity module.
> Added patch for issues in the entity module.

- modules/features/sesi_my_queries_screen/sesi_my_queries_screen.views_default.inc
- seldrush.py
> changes for sesidev-260

- modules/query_ontologies/query_ontologies.taxonomy_tree.js
Every node that matches the search (and has no parent node that matches) will be expanded
> Changed the method to filter ontology tree

- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_query/mica_query.terms.inc
This implements a DateTerm class, deriving RangeTerm. Querying date ranges is now supported, and date constraints in queries now have useful validation.
> Implement DateTerm, fix USESI-166, USESI-154

- patch/mica_distribution/modules/search_api_ranges/search_api_ranges.module
SESIDEV_266
SESIDEV_267
SESIDEV_268
> SESIDEV_266_267_268

- drupalpull.php
The first line "<?php" is not needed and gives me errors.
> minor changes in drupalpull.php to have better output

- modules/features/sesi_communities_and_files/sesi_communities_and_files.features.field_instance.inc
- modules/features/sesi_communities_and_files/sesi_communities_and_files.features.og_features_permission.inc
- modules/features/sesi_communities_and_files/sesi_communities_and_files.info
Fixes LP-60
This PR still needs to be checked to verify that the feature changes are the right ones.
> Make studies be invisible in hidden groups

- modules/features/sesi_communities_and_files/sesi_communities_and_files.features.features_overrides.inc
- modules/features/sesi_communities_and_files/sesi_communities_and_files.features.inc
- modules/features/sesi_communities_and_files/sesi_communities_and_files.info
> Set Community accesibility default to private

- modules/features/sesi_communities_and_files/sesi_communities_and_files.views_default.inc
so our custom access check sees all communities
Fixes USESI-268
> Disable default access checks on Communities view

- modules/prepopulate_group_ref/prepopulate_group_ref.module
> Fix setting the group audience automatically when creating new community content

- modules/query_subscription/query_subscription.module
- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_connector/mica_connector.connection.form.inc
- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_connector/mica_connector.module
- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_query/mica_query.pages.crosstab.inc
- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_query/mica_query.pages.inc
- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_query/mica_query.terms.inc
> Dataset access

- modules/features/sesi_variable_search_wildcards/sesi_variable_search_wildcards.features.features_overrides.inc
- modules/features/sesi_variable_search_wildcards/sesi_variable_search_wildcards.features.inc
- modules/sesi_wildcard_search_processor/sesi_wildcard_search_processor.module
Interpret underscores as regular word characters
USESI-278
> Underscore search

- modules/features/sesi_communities_and_files/sesi_communities_and_files.features.field_base.inc
- seldrush.py
> Make 'Project visibility' field visible to community admins

- patch/mica_distribution/themes/mica_bootstrap/template.php
For USESI-238. Merging this should wait until Ludwig / CMI agrees to the design.
> Username on menu

- patch/mica_distribution/modules/mica/extensions/mica_datasets/mica_connector/mica_connector.pages.inc
> Fix another instance of double encoding
